import smtplib
from getpass import getpass

# get email information from user
# sender_name = input('\nEnter the sender name\n')

def send_email(data):
    #Temporary may need to obtain the these thru a file/sokcets generated by the radio files
    sender_email = data['From']
    recipient_email = data['To'] 
    pw = data['pass']

    # connect to email server (outlook being used here) and authenticate
    server = smtplib.SMTP(host ='smtp-mail.outlook.com' ,port= 587)
    # put the SMTP connection in TLS mode, all SMTP commands that follow will be encrypted
    server.starttls()

    # try to authenticate with email server
    try:
        server.login(user = sender_email, password = pw)
    except smtplib.SMTPAuthenticationError as e:
        # authenctication error
        print(f'Error: {e}')
        quit()
        
    subject = data['Subject']
    body = data['Body']

    # "From", "To", and "Subject" headers for the email
    msg = f'Subject: {subject}\r\nFrom: {sender_email}\r\nTo: {recipient_email}\r\n\r\n{body}'
    # msg = f'From: {sender_name} <{sender_email}>\r\nTo: {recipient_email}\r\nSubject: {subject}\r\n\r\n{body}'

    try:
        server.sendmail(sender_email, recipient_email, msg)
        print('Email sent successfully')
    except Exception as e:
        print(f'Error: {e}')

    server.quit()
